# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://merkinov:Mirpolat0922@cluster0.lwezjig.mongodb.net/newUsers?retryWrites=true&w=majority&appName=Cluster0
# No need for separate host/port/database with URI
# Auto index and other configurations remain the same
spring.data.mongodb.auto-index-creation=true

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG